export const LEARNING_LEVELS = [
  {
    level: 1,
    title: "句子基础",
    titleEn: "Sentence Basics",
    description: "先把人物、时间、地点和动作写清楚。",
    descriptionEn: "Write clearly who, when, where and what happened.",
  },
  {
    level: 2,
    title: "句型变化",
    titleEn: "Pattern Variation",
    description: "保留句型骨架，更换人物、地点和事情。",
    descriptionEn: "Keep the sentence frame but change the person, place and event.",
  },
  {
    level: 3,
    title: "生动表达",
    titleEn: "Vivid Expression",
    description: "加入连续动作、心情反应和自然对话。",
    descriptionEn: "Add action sequences, reactions and natural dialogue.",
  },
  {
    level: 4,
    title: "段落连接",
    titleEn: "Paragraph Flow",
    description: "把几句话按照事情的发展连接起来。",
    descriptionEn: "Connect sentences in the order the event develops.",
  },
  {
    level: 5,
    title: "作文训练",
    titleEn: "Composition Practice",
    description: "把通顺句子运用在完整作文中。",
    descriptionEn: "Apply clear sentences in a complete composition.",
  },
];

export const LANGUAGE_DIFFERENCES = [
  {
    number: "01",
    title: "时间和地点通常放在动作前面",
    titleEn: "Time and place usually come before the action",
    english: "I revised my work in the library after school.",
    chinese: "放学后，我在图书馆里温习功课。",
    explanation: "中文通常先交代什么时候、在哪里，然后才写人物做什么。",
    explanationEn: "Chinese usually sets the time and place before stating the action.",
  },
  {
    number: "02",
    title: "形容的内容放在名词前面",
    titleEn: "Descriptions come before the noun",
    english: "I saw a boy who was wearing a blue uniform.",
    chinese: "我看见一个穿着蓝色校服的男孩。",
    explanation: "“穿着蓝色校服的”放在“男孩”前面，说明是哪一个男孩。",
    explanationEn: "The description comes before 男孩 to show which boy is being described.",
  },
  {
    number: "03",
    title: "动作的方式放在动词前面",
    titleEn: "How an action is done comes before the verb",
    english: "He quickly ran over.",
    chinese: "他连忙跑过去。",
    explanation: "“连忙”说明他怎样跑，所以放在动作“跑”之前。",
    explanationEn: "连忙 explains how he ran, so it appears before the verb 跑.",
  },
  {
    number: "04",
    title: "按照动作发生的顺序来写",
    titleEn: "Write actions in the order they happen",
    english: "He bent down, picked up the wallet and gave it to the teacher.",
    chinese: "他弯下腰，捡起钱包，然后把它交给老师。",
    explanation: "读者会像看电影一样，跟着人物一步一步完成动作。",
    explanationEn: "The reader can follow the character's actions one step at a time.",
  },
  {
    number: "05",
    title: "关联词经常成双使用",
    titleEn: "Connectors are often used in pairs",
    english: "Although it was raining, we continued to wait.",
    chinese: "虽然下着大雨，但是我们仍然继续等候。",
    explanation: "记住完整搭配：因为……所以……、虽然……但是……、不但……还……",
    explanationEn: "Learn the complete pairs: because–therefore, although–but, and not only–also.",
  },
  {
    number: "06",
    title: "人物必须清楚",
    titleEn: "Make the person doing the action clear",
    english: "Ming saw Zhi fall, so he ran over to help him.",
    chinese: "小明看见志强跌倒，便连忙跑过去扶起他。",
    explanation: "使用“他”时，要让读者清楚知道“他”指的是谁。",
    explanationEn: "When using 他, make sure the reader can tell clearly who it refers to.",
  },
];

export const NOTEBOOK_CATEGORIES = [
  {
    number: 1,
    title: "时间和地点",
    titleEn: "Time and Place",
    pattern: "时间＋人物＋地点＋动作",
    patternEn: "When + Who + Where + Action",
    example: "星期六早上，我和爸爸到公园里骑脚踏车。",
    explanation: "先让读者知道事情什么时候、在哪里发生。",
    explanationEn: "First tell the reader when and where the event happened.",
  },
  {
    number: 2,
    title: "发现问题",
    titleEn: "Discovering a Problem",
    pattern: "看到／发现＋发生了什么",
    patternEn: "Saw / Discovered + What happened",
    example: "走到楼梯口时，我发现一位老奶奶跌坐在地上。",
    explanation: "清楚写出人物看见或发现了什么问题。",
    explanationEn: "State clearly what problem the character noticed or discovered.",
  },
  {
    number: 3,
    title: "人物动作",
    titleEn: "Character Actions",
    pattern: "走近＋动作一＋动作二＋完成",
    patternEn: "Approach + Action 1 + Action 2 + Finish",
    example: "我连忙跑过去，弯下腰，把地上的书一本一本捡起来。",
    explanation: "把动作拆开，并按照发生的顺序来写。",
    explanationEn: "Break the action into steps and write them in the order they happen.",
  },
  {
    number: 4,
    title: "心情反应",
    titleEn: "Feelings and Reactions",
    pattern: "发生什么＋身体反应＋心里想法",
    patternEn: "What happened + Physical reaction + Inner thought",
    example: "看到眼前的一幕，我顿时愣住了，一时不知该怎么办。",
    explanation: "不要只写“很紧张”，也写出人物的动作或身体反应。",
    explanationEn: "Do not only name the feeling; show the character's action or physical reaction.",
  },
  {
    number: 5,
    title: "对话",
    titleEn: "Dialogue",
    pattern: "人物动作＋说话语气＋说话内容",
    patternEn: "Character action + Tone + Spoken words",
    example: "我走上前，轻声问道：“你需要帮忙吗？”",
    explanation: "在对话前加入动作和语气，让说话听起来自然。",
    explanationEn: "Add an action and tone before the dialogue to make it sound natural.",
  },
  {
    number: 6,
    title: "解决问题",
    titleEn: "Solving the Problem",
    pattern: "想办法＋采取行动＋事情结果",
    patternEn: "Think of a solution + Take action + Result",
    example: "我请同学照顾老奶奶，自己则赶紧到办公室通知老师。",
    explanation: "写清楚人物怎样处理问题，以及事情最后怎样了。",
    explanationEn: "Explain how the character handled the problem and what happened afterward.",
  },
  {
    number: 7,
    title: "感想和结尾",
    titleEn: "Reflection and Ending",
    pattern: "事情结果＋学到的道理／以后会怎样",
    patternEn: "Result + Lesson learnt / What I will do next time",
    example: "这件事让我明白，只要大家愿意伸出援手，就能让生活变得更温暖。",
    explanation: "结尾要和事情有关，不必使用太长或太深奥的道理。",
    explanationEn: "Keep the ending connected to the event; the lesson does not need to sound complicated.",
  },
];
